version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: cargo run
    ports:
      - "4000:4000"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_REGION=julia-home
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    links:
      - dynamodb
    networks:
      internal_net:
        ipv4_address: 172.21.1.2

  dynamodb:
    container_name: "dynamodb"
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      internal_net:
        ipv4_address: 172.21.1.1
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    volumes:
      - dynamodata:/home/dynamodblocal/
    working_dir: /home/dynamodblocal/
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

networks:
  internal_net:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

volumes:
  dynamodata: